### ISSUE TITLE
BioLogic: Unexpected end of file while reading data current module: b'VMP settings

### ISSUE THREAD

**Issue by joenoula** [echemdata/galvani#108]
I'm running into this error whenever i try to read any .mpr files using the BioLogic function. I'm trying to read EC-Lab files and I'm pretty new to python any help would be appreciated. Thanks!

**Comment by ml-evs** [comment]
See https://github.com/echemdata/galvani/issues/87, BioLogic changed the MPR format after ECLab 11.50 and we only recently added support for it. If you install directly from this repository (with e.g. `pip install git+https://github.com/echemdata/galvani` it should work fine, otherwise you will need to wait for a release to be made on PyPI.
